// List of topics
const topics = [
    { id: 'family', name: 'Chủ đề gia đình', fileName: 'family_vocabulary.json' },
    { id: 'weather', name: 'Chủ đề thời tiết', fileName: 'weather_vocabulary.json' },
    { id: 'job', name: 'Chủ đề nghề nghiệp', fileName: 'job_vocabulary.json' },
    { id: 'clothes', name: 'Chủ đề quần áo đầy đủ nhất', fileName: 'clothes_vocabulary.json' },
    { id: 'character', name: 'Chủ đề tính cách', fileName: 'character_vocabulary.json' },
    { id: 'vegetable', name: 'Chủ đề rau củ', fileName: 'vegetable_vocabulary.json' },
    { id: 'environment', name: 'Chủ đề môi trường', fileName: 'environment_vocabulary.json' },
    { id: 'animals', name: 'Chủ đề con vật', fileName: 'animals_vocabulary.json' },
    { id: 'food', name: '   Chủ đề đồ ăn', fileName: 'food_vocabulary.json' },
    { id: 'school', name: 'Chủ đề trường học đầy đủ nhất', fileName: 'school_vocabulary.json' },
    { id: 'travel', name: 'Chủ đề du lịch', fileName: 'travel_vocabulary.json' },
    { id: 'color', name: 'Chủ đề màu sắc', fileName: 'color_vocabulary.json' },
    { id: 'trafic', name: 'Chủ đề giao thông', fileName: 'trafic_vocabulary.json' },
    { id: 'feeling', name: 'Chủ đề cảm xúc', fileName: 'feeling_vocabulary.json' },
    { id: 'fruits', name: 'Chủ đề hoa quả', fileName: 'fruits_vocabulary.json' },
    { id: 'work', name: 'Chủ đề công việc', fileName: 'work_vocabulary.json' },
    { id: 'christermas', name: 'Chủ đề giáng sinh', fileName: 'christermas_vocabulary.json' },
    { id: 'fashion', name: 'Chủ đề thời trang', fileName: 'fashion_vocabulary.json' },
    { id: 'middleautum', name: 'Chủ đề trung thu', fileName: 'middleautum_vocabulary.json' },
    { id: 'kitchen', name: 'Chủ đề nhà bếp', fileName: 'kitchen_vocabulary.json' },
    { id: 'sport', name: 'Chủ đề các môn thể thao', fileName: 'sport_vocabulary.json' },
    { id: 'drink', name: 'Chủ đề thức uống', fileName: 'drink_vocabulary.json' },
    { id: 'descripbepeople', name: 'Chủ đề miêu tả người', fileName: 'descripbepeople_vocabulary.json' },
    { id: 'country', name: 'Chủ đề quốc gia', fileName: 'country_vocabulary.json' },
    { id: 'insects', name: 'Chủ đề côn trùng', fileName: 'insects_vocabulary.json' },
    { id: 'football', name: 'Chủ đề bóng đá đầy đủ nhất', fileName: 'football_vocabulary.json' },
    { id: 'stores', name: 'Chủ đề cửa hàng', fileName: 'stores_vocabulary.json' },
    { id: 'hometown', name: 'Chủ đề quê hương', fileName: 'hometown_vocabulary.json' },
    { id: 'tet', name: 'Chủ đề Tết', fileName: 'newyear_vocabulary.json' },
    { id: 'schoolsupplies', name: 'Chủ đề đồ dùng học tập', fileName: 'schoolsuplies_vocabulary.json' },
    { id: 'bodyaction', name: 'Chủ đề hành động cơ thể người', fileName: 'bodyaction_vocabulary.json' },
    { id: 'dailyactivity', name: 'Chủ đề hoạt động hàng ngày', fileName: 'dailyactivity_vocabulary.json' },
    { id: 'numbers', name: 'Chủ đề số đếm', fileName: 'number_vocabulary.json' },
    { id: 'shopping', name: 'Chủ đề mua sắm', fileName: 'shopping_vocabulary.json' },
    { id: 'hospital', name: 'Chủ đề bệnh viện', fileName: 'hospital_vocabulary.json' },
    { id: 'health', name: 'Chủ đề sức khoẻ', fileName: 'health_vocabulary.json' },
    { id: 'flowers', name: 'Chủ đề các loài hoa', fileName: 'flower_vocabulary.json' },
    { id: 'movies', name: 'Chủ đề phim ảnh', fileName: 'movie_vocabulary.json' },
    { id: 'seafood', name: 'Chủ đề hải sản', fileName: 'fish_vocabulary.json' },
    { id: 'postoffice', name: 'Chủ đề bưu điện', fileName: 'postoffice_vocabulary,.json' },
    { id: 'bank', name: 'Chủ đề ngân hàng', fileName: 'bank_vocabulary.json' }
];

// Bootstrap's built-in functionality handles the tab switching,
// so no additional JavaScript is needed for basic functionality.
// This file is mainly for storing the topic data.

console.log('Topics loaded:', topics);
